apiVersion: v1
kind: Pod
metadata: 
    name: producer-pod
spec:
    volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
              claimName: task-pv-claim2
    containers:
        - name: consumer-pod
          image: sudhanshu457/producer:latest
          env:
            - name: cacert
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: cacert
            - name: producercert
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: producercert
            - name: producerkey
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: producerkey
            - name: hostname
              value: 'rabbitmq-node-port'
          volumeMounts:
            - name: task-pv-storage
              mountPath: "/certificate/producer"
              subPath: "producer-server-certificate"
            - name: task-pv-storage
              mountPath: "/certificate/CA"
              subPath: "Trusted-CA"
            - name: task-pv-storage
              mountPath: "/usr/src/app/logs"
              subPath: "logs"

            
