apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
type: Opaque
stringData:
  cacert: '/certificate/CA/CA-cert.pem'
  consumercert: '/certificate/consumer/consumer-cert.pem'
  consumerkey: '/certificate/consumer/consumer-key.pem'