apiVersion: v1
kind: Service
metadata:
    name: ca-cluster-ip-service
spec:
    type: ClusterIP
    ports:
        - protocol: "TCP"
          name: management-console  # by default protocol is tcp
          port: 5000
          targetPort: 5000
    selector:
        app: ca