apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-deployment
    labels:
        app: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            volumes:
                - name: task-pv-storage
                  persistentVolumeClaim:
                     claimName: task-pv-claim
            containers:
                - name: rabbitmq
                  image: sudhanshu457/rabbitmq
                  ports:
                    - name: without-ssl
                      containerPort: 5672
                    - name: with-ssl
                      containerPort: 5671
                  volumeMounts:
                    - name: task-pv-storage
                      mountPath: "/certificate/rabbitmq"
                      subPath: "Rabbitmq-server-certificate"
                    - name: task-pv-storage
                      mountPath: "/certificate/CA"
                      subPath: "Trusted-CA"

                    
        
