apiVersion: v1
kind: Service
metadata:
  name: expose-rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  type: LoadBalancer