apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    service: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    name: client
    targetPort: 9200
    nodePort: 30005
  - port: 9300
    name: nodes
  selector:
    app: elasticsearch