apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificateauthoritys.cp.info
spec:
  scope: Namespaced
  group: cp.info
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  names:
    kind: CertificateAuthority
    plural: certificateauthoritys
    singular: certificateauthority
    shortNames:
      - ca
