apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-cluster-ip-service
spec:
    type: NodePort
    ports:
        - name: management-console
          port: 3055
          targetPort: 15672
        - protocol: TCP
          name: client-connection
          port: 5672
          targetPort: 5672 
        - protocol: TCP
          name: client-connection-ssl
          port: 5671
          targetPort: 5671  
         
    selector:
        app: rabbitmq